version: '3.4'

services:
  db:
    image: microsoft/mssql-server-linux
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Password123"
    volumes:
      - ./db-data:/var/lib/db
    restart: always
    networks:
      - onlinestore-net

  onlinestore:
    image: ${DOCKER_REGISTRY-}onlinestore
    build:
      context: .
      dockerfile: OnlineStore/Dockerfile
    depends_on:
      - db
    networks:
      - onlinestore-net

  frontend:
    image: node:11
    volumes:
      - ./front:/usr/src/service
    working_dir: /usr/src/service
    command: npm run frontend
    ports:
      - 1234:1234
      - 1235:1235
    networks:
      - onlinestore-net

volumes:
  db-data:
  front:
networks:
  onlinestore-net:
    driver: bridge
