version: '3.4'

services:
  db:
    image: microsoft/mssql-server-linux
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "1qazXSW@"
    volumes:
      - ./db-data:/var/lib/db
    restart: always
    networks:
      - onlinestore-net

  onlinestore:
    image: ${DOCKER_REGISTRY-}onlinestore
    build:
      context: .
      dockerfile: OnlineStore/Dockerfile
    depends_on:
      - db
    networks:
      - onlinestore-net

volumes:
  db-data:
networks:
  onlinestore-net:
    driver: bridge
